In [9]:
import numpy as np

import torch

from transformers import (
    DistilBertTokenizer,
    DistilBertForSequenceClassification
)

from revllm_copy.sentiment_analyze_distilbert import sentiment_analysis, qAndA
from revllm_copy.sentiment_preprocess import DistilbertSentimentPreprocesser

In [10]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"

In [11]:
preprocessor = DistilbertSentimentPreprocesser(model_name)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)
# analyzer = qAndA(model_name, preprocessor)

In [41]:
context = "I gotta say it was a good day."

In [42]:
preprocessor(context)

In [44]:
print(preprocessor.input_ids)
print(preprocessor.baseline_input_ids)
print(preprocessor.attention_mask)
print(preprocessor.all_tokens)

tensor([[  101,  1045, 10657,  2360,  2009,  2001,  1037,  2204,  2154,  1012,
           102]])
tensor([[101,   0,   0,   0,   0,   0,   0,   0,   0,   0, 102]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
['[CLS]', 'i', 'gotta', 'say', 'it', 'was', 'a', 'good', 'day', '.', '[SEP]']


# Just to see

In [46]:
model = DistilBertForSequenceClassification.from_pretrained(model_name)

In [52]:
def predict(input_ids, attention_mask):
    output = model(input_ids, attention_mask=attention_mask)
    logits = output.logits

    return logits[0]

predict(preprocessor.input_ids, preprocessor.attention_mask)

tensor([-3.9981,  4.3832], grad_fn=<SelectBackward0>)

In [53]:
context = "I gotta say it was a bad day."
preprocessor(context)
predict(preprocessor.input_ids, preprocessor.attention_mask)

tensor([ 4.6871, -3.8036], grad_fn=<SelectBackward0>)

# For Comparison

In [49]:
# # Load tokenizer and model
# MODEL_NAME = "distilbert-base-uncased-finetuned-sst-2-english"
# tokenizer = DistilBertTokenizer.from_pretrained(MODEL_NAME)
# model = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME)

# # Function to predict sentiment
# def predict_sentiment(text):
#     # Tokenize input text and get tensor outputs
#     inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
#     with torch.no_grad():
#         outputs = model(**inputs)
#     logits = outputs.logits
#     probs = torch.nn.functional.softmax(logits, dim=-1)
#     predicted_class = torch.argmax(probs, dim=-1).item()
    
#     # Convert to positive/negative labels
#     labels = ['negative', 'positive']
#     return labels[predicted_class]

# # Test
# text = "I love this product!"
# result = predict_sentiment(text)
# print(f"The sentiment for '{text}' is: {result}")
